version: '3.8'

services:
  web:
    build: ./app
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    image: blog_dev
    restart: always
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    container_name: pg_container
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_dev
      - POSTGRES_PASSWORD=django_dev
      - POSTGRES_DB=django_dev
    ports:
      - "5432:5432"

  pgadmin:
    user: root
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin/:/var/lib/pgadmin/
    ports:
      - "5050:80"
      
volumes:
  postgres_data_dev: