version: '3.8'

services:
  web:
    build:  
      context: ./app
      dockerfile: Dockerfile.prod
    image: blog_prod
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - blog_static_files:/home/app/web/staticfiles
      - ./app/mediafiles:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
    expose:
      - 5432
      
  nginx:
    build: ./nginx
    image: blog_nginx
    volumes:
      - blog_static_files:/home/app/web/staticfiles
      - ./app/mediafiles:/home/app/web/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    env_file:
      - ./.env.prod.db
    volumes:
      - ./pgadmin/:/var/lib/pgadmin/ 
    ports:
      - 5050:80   

volumes:
  postgres_data:
  blog_static_files: