version: '3.8'

services:
  web:
    build:  
      context: ./app
      dockerfile: Dockerfile.prod
    image: blog_prod
    command: gunicorn blog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - blog_static_files:/home/app/web/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    image: blog_nginx
    volumes:
      - blog_static_files:/home/app/web/staticfiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      
volumes:
  postgres_data:
  blog_static_files: