version: '3.8'

services:
  web:
    build: ./app
    command: pipenv run python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/blog/:/usr/src/app/blog/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_dev
      - POSTGRES_PASSWORD=django_dev
      - POSTGRES_DB=django_dev
      
volumes:
  postgres_data_dev: