# Generated by Django 4.0.3 on 2022-03-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeExp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code_type', models.IntegerField(choices=[(0, 'Language'), (1, 'Technology'), (2, 'Web'), (3, 'DB'), (4, 'IDE'), (5, 'Concept'), (6, 'Testing'), (7, 'Gamedev'), (8, 'Other')], default=0)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
