# Generated by Django 4.0.3 on 2022-04-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0004_alter_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.IntegerField(choices=[(0, 'Current'), (1, 'Archive'), (2, 'Library')], default=0),
        ),
    ]
